"use client"
import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Nav from '@components/Nav';
import Footer from '@components/Footer';
const inter = Inter({ subsets: ['latin'] })
import { Providers } from '@/redux/providers'
import {theme} from './theme/themes'
import { ThemeProvider, CssBaseline, Switch, FormControlLabel } from "@mui/material";
export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <ThemeProvider theme={theme}>
        <CssBaseline />
        <body className={inter.className} id="__next">
          <CssBaseline />
          <div className="desktop">
            <Nav />
            <div className='container'>
              {children}
            </div>
            <Footer />
          </div>

        </body>
        </ThemeProvider>

      </html>
    </Providers>
  )
}
